// <auto-generated />
using System;
using MangaUs.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MangaUS.Migrations
{
    [DbContext(typeof(MangaDbContext))]
    [Migration("20240920013311_DbManga")]
    partial class DbManga
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MangaUs.Models.Capitulo", b =>
                {
                    b.Property<int>("CapituloId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CapituloId"));

                    b.Property<DateTime>("DtCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<int>("MangaId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroCapitulo")
                        .HasColumnType("int");

                    b.HasKey("CapituloId");

                    b.HasIndex("MangaId");

                    b.ToTable("Capitulos");
                });

            modelBuilder.Entity("MangaUs.Models.Favorito", b =>
                {
                    b.Property<int>("FavoritoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FavoritoId"));

                    b.Property<DateTime>("DtCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<int>("MangaId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("FavoritoId");

                    b.HasIndex("MangaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Favoritos");
                });

            modelBuilder.Entity("MangaUs.Models.Genero", b =>
                {
                    b.Property<int>("GeneroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GeneroId"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("GeneroId");

                    b.ToTable("Generos");
                });

            modelBuilder.Entity("MangaUs.Models.Manga", b =>
                {
                    b.Property<int>("MangaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MangaId"));

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CapaManga")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DtCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("MangaId");

                    b.HasIndex("GeneroId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Mangas");
                });

            modelBuilder.Entity("MangaUs.Models.Pagina", b =>
                {
                    b.Property<int>("PaginaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaginaId"));

                    b.Property<int>("CapituloId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DtCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<int>("NumeroPagina")
                        .HasColumnType("int");

                    b.Property<string>("UrlImagem")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("PaginaId");

                    b.HasIndex("CapituloId");

                    b.ToTable("Paginas");
                });

            modelBuilder.Entity("MangaUs.Models.ProgressoLeitura", b =>
                {
                    b.Property<int>("ProgressoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgressoId"));

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2");

                    b.Property<int>("CapituloId")
                        .HasColumnType("int");

                    b.Property<int>("MangaId")
                        .HasColumnType("int");

                    b.Property<int>("NumeroPagina")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("ProgressoId");

                    b.HasIndex("CapituloId");

                    b.HasIndex("MangaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("ProgressoLeituras");
                });

            modelBuilder.Entity("MangaUs.Models.Usuario", b =>
                {
                    b.Property<int>("UsuarioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UsuarioId"));

                    b.Property<DateTime>("DtCriacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeUsuario")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("TipoUsuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UsuarioId");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("MangaUs.Models.Capitulo", b =>
                {
                    b.HasOne("MangaUs.Models.Manga", "Manga")
                        .WithMany("Capitulos")
                        .HasForeignKey("MangaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manga");
                });

            modelBuilder.Entity("MangaUs.Models.Favorito", b =>
                {
                    b.HasOne("MangaUs.Models.Manga", "Manga")
                        .WithMany("Favoritos")
                        .HasForeignKey("MangaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MangaUs.Models.Usuario", "Usuario")
                        .WithMany("Favoritos")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Manga");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MangaUs.Models.Manga", b =>
                {
                    b.HasOne("MangaUs.Models.Genero", "Genero")
                        .WithMany("Mangas")
                        .HasForeignKey("GeneroId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaUs.Models.Usuario", "Usuario")
                        .WithMany("Mangas")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Genero");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MangaUs.Models.Pagina", b =>
                {
                    b.HasOne("MangaUs.Models.Capitulo", "Capitulo")
                        .WithMany("Paginas")
                        .HasForeignKey("CapituloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Capitulo");
                });

            modelBuilder.Entity("MangaUs.Models.ProgressoLeitura", b =>
                {
                    b.HasOne("MangaUs.Models.Capitulo", "Capitulo")
                        .WithMany()
                        .HasForeignKey("CapituloId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaUs.Models.Manga", "Manga")
                        .WithMany("ProgressoLeituras")
                        .HasForeignKey("MangaId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("MangaUs.Models.Usuario", "Usuario")
                        .WithMany("ProgressoLeituras")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Capitulo");

                    b.Navigation("Manga");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MangaUs.Models.Capitulo", b =>
                {
                    b.Navigation("Paginas");
                });

            modelBuilder.Entity("MangaUs.Models.Genero", b =>
                {
                    b.Navigation("Mangas");
                });

            modelBuilder.Entity("MangaUs.Models.Manga", b =>
                {
                    b.Navigation("Capitulos");

                    b.Navigation("Favoritos");

                    b.Navigation("ProgressoLeituras");
                });

            modelBuilder.Entity("MangaUs.Models.Usuario", b =>
                {
                    b.Navigation("Favoritos");

                    b.Navigation("Mangas");

                    b.Navigation("ProgressoLeituras");
                });
#pragma warning restore 612, 618
        }
    }
}
